scrape_configs:
  - job_name: node-exporter
    scrape_interval: 60s
    static_configs:
    - targets: ['node-exporter:9100']
  - job_name: prometheus
    honor_labels: true
    static_configs:
      - targets: [ 'localhost:9090' ]
        labels:
          instance: prometheus

remote_write:
 - url: http://thanos-receive:10908/api/v1/receive
