type: S3
config:
  bucket: prometheusthanos
  endpoint: minio:9000
  access_key: admin
  insecure: true
  signature_version2: false
  secret_key: bucketsecret
  put_user_metadata: {}
  http_config:
    idle_conn_timeout: 1m30s
    response_header_timeout: 2m
    insecure_skip_verify: false
    tls_handshake_timeout: 10s
    expect_continue_timeout: 1s
    max_idle_conns: 100
    max_idle_conns_per_host: 100
    max_conns_per_host: 0